#  This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build_and_test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          which python3
          python3 --version
          docker --version
          which docker-compose
          docker-compose --version
          pwd
          ls -al
          
      - name: clone the aa-hacking repo
        run: git clone https://github.com/jctanner/aa-hacking
      
      - name: make the venv
        run: |
          pwd
          ls -al
          pip3 install --user virtualenv
          python3 -m virtualenv --python=$(which python3) venv
          source venv/bin/activate
          pip install -r requirements.txt
        working-directory: ./aa-hacking

      - name: make the stack
        run: |
          source venv/bin/activate
          make stack_ci_cypress
        working-directory: ./aa-hacking
        
      - name: save the screenshots 
        uses: actions/upload-artifact@v2
        with:
          name: screens
          path: ./aa-hacking/srv/integration_tests/screens
          retention-days: 5
        if: always()
